name = "PowerSpectrumNoises"
uuid = "6ab34832-f7e5-40a4-9cd7-47ea82b5c144"
authors = ["Anna Tartaglia", "Kazunori Akiyama"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
